### ISSUE TITLE
Multiple logos on cover slide

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert-talks/talk-pyhep-dev-2023#3]
Apparently the way that I tried to add the IRIS-HEP logo to the cover slide

https://github.com/matthewfeickert-talks/talk-pyhep-dev-2023/blob/c941e9b2656fe4468e747601b93ebf36a7bd6bea/slides.md?plain=1#L30-L33

https://github.com/matthewfeickert-talks/talk-pyhep-dev-2023/blob/c941e9b2656fe4468e747601b93ebf36a7bd6bea/slides.md?plain=1#L42-L43

works in the web view but when Vue exports to PDF it ends up adding the logo to every slide.

Example: [Slide 2](https://matthewfeickert-talks.github.io/talk-pyhep-dev-2023/2)

![Screenshot from 2023-07-25 11-25-00](https://github.com/matthewfeickert-talks/talk-pyhep-dev-2023/assets/5142394/84faba18-7718-421d-8389-0fd57e782552)

@klieret My guess is I'm doing something pretty obviously wrong, so if you happen to have suggestions here that would be great.

**Comment by klieret** [comment]
Hmm, not sure with the PDF export... I don't see anything obviously wrong there. Could it be something with the `position: fixed`?
